# Generated by Django 4.1.4 on 2023-06-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=11)),
                ('Email', models.EmailField(max_length=254)),
                ('Department', models.TextField(max_length=20)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
